### ISSUE TITLE
Crash on unowned tags

### ISSUE THREAD

**Issue by Doridian** [Doridian/factorio-fox-todo#13]

**Comment by Doridian** [comment]
Possible fix for this in 0.2.2

**Comment by CapsParrot** [comment]
![Error](https://github.com/Doridian/factorio-fox-todo/assets/148323071/05400068-ff1c-4496-af33-29fa70d3eac9)

**Comment by Doridian** [comment]
@CapsParrot Neat, yep, this should be fixed in 0.2.2! Let me know if it works for you.

**Comment by CapsParrot** [comment]
Yes it has been fixed :D
